name: MethyLasso
channels:
  - conda-forge
  - r
  - bioconda
  - defaults
dependencies:
  - r-base=4.3.3
  - r-essentials=4.3
  - r-rcppeigen=0.3.4.0.0
  - r-rcppgsl=0.3.13
  - r-bh=1.84.0_0
  - r-doparallel=1.0.17
  - r-ggrepel=0.9.5
  - r-data.table=1.15.4
  - r-foreach=1.5.2
  - r-ggplot2=3.5.1
  - r-scales=1.3.0
  - r-matrix=1.6_5
  - r-matrixstats=1.3.0
  - r-r.utils=2.12.3
  
